name: 0.Git/ PR Test
on:
  workflow_dispatch:
env:
  github_token: ${{ secrets.GIT_HUB_TOKEN }}
  provisioning_token: ${{ secrets.PROVISIONING_TOKEN }}
jobs:
  loadenv:
    name: serup pipeline Enviroment
    runs-on: ubuntu-latest
    outputs:
      hasSB: ${{ steps.loadEnvStep.outputs.hasSB }}
      requireBuild: ${{ steps.loadEnvStep.outputs.requireBuild }}
      lang: ${{ steps.loadEnvStep.outputs.lang }}
